costTier = {
	usd: [
		795,	// dice
		1495,	// small-based ship
		1995,	// small-based ship+
		2995,	// large-based ship
		3995,	// large-based ship+
		4995,	// Ghost
		5995,	// Rebel Transport
		6995,	// Imperial Assault Carrier
		7995,	// -
		8995,	// Tantive IV
		9995,	// Imperial Raider
	],
	gbp: [
		699,	// dice, bases
		1199,	// small-based ship
		1699,	// small-based ship+
		2499,	// large-based ship
		2999,	// large-based ship+
		3999,	// Ghost
		4999,	// Rebel Transport
		6499,	// Imperial Assault Carrier
		6999,	// -
		7499,	// Tantive IV
		7999,	// Imperial Raider
	]
};

swx = [
	{"null": []},
	{"Core Set": [
		{name: "TIE Fighter", type: "ship", qty: 2},
		{name: "X-Wing", type: "ship", qty: 1},
		{name: '"Dark Curse"', type: "pilot", qty: 1},
		{name: '"Mauler Mithel"', type: "pilot", qty: 1},
		{name: '"Night Beast"', type: "pilot", qty: 1},
		{name: "Biggs Darklighter", type: "pilot", qty: 1},
		{name: "Luke Skywalker", type: "pilot", qty: 1},
		{name: "Academy Pilot", type: "pilot", qty: 2},
		{name: "Black Squadron Pilot", type: "pilot", qty: 2},
		{name: "Obsidian Squadron Pilot", type: "pilot", qty: 2},
		{name: "Red Squadron Pilot", type: "pilot", qty: 1},
		{name: "Rookie Pilot", type: "pilot", qty: 1},
		{name: "R2-D2", type: "astromech", qty: 1},
		{name: "R2-F2", type: "astromech", qty: 1},
		{name: "Determination", type: "elite", qty: 1},
		{name: "Marksmanship", type: "elite", qty: 1},
		{name: "Proton Torpedoes", type: "torpedo", qty: 1}
	],
	cost: 4},
	{"X-Wing Expansion Pack": [
		{name: "X-Wing", type: "ship", qty: 1},
		{name: "Garven Dreis", type: "pilot", qty: 1},
		{name: "Wedge Antilles", type: "pilot", qty: 1},
		{name: "Red Squadron Pilot", type: "pilot", qty: 1},
		{name: "Rookie Pilot", type: "pilot", qty: 1},
		{name: "R5 Astromech", type: "astromech", qty: 1},
		{name: "R5-K6", type: "astromech", qty: 1},
		{name: "Expert Handling", type: "elite", qty: 1},
		{name: "Marksmanship", type: "elite", qty: 1},
		{name: "Proton Torpedoes", type: "torpedo", qty: 1}
	],
	cost: 1},
	{"TIE Fighter Expansion Pack": [
		{name: "TIE Fighter", type: "ship", qty: 1},
		{name: '"Backstabber"', type: "pilot", qty: 1},
		{name: '"Howlrunner"', type: "pilot", qty: 1},
		{name: '"Winged Gundark"', type: "pilot", qty: 1},
		{name: "Academy Pilot", type: "pilot", qty: 1},
		{name: "Black Squadron Pilot", type: "pilot", qty: 1},
		{name: "Obsidian Squadron Pilot", type: "pilot", qty: 1},
		{name: "Determination", type: "elite", qty: 1},
		{name: "Swarm Tactics", type: "elite", qty: 1}
	],
	cost: 1},
	{"Y-Wing Expansion Pack": [
		{name: "Y-Wing", type: "ship", qty: 1},
		{name: '"Dutch" Vander', type: "pilot", qty: 1},
		{name: "Horton Salm", type: "pilot", qty: 1},
		{name: "Gold Squadron Pilot", type: "pilot", qty: 1},
		{name: "Gray Squadron Pilot", type: "pilot", qty: 1},
		{name: "R2 Astromech", type: "astromech", qty: 1},
		{name: "R5-D8", type: "astromech", qty: 1},
		{name: "Proton Torpedoes", type: "torpedo", qty: 2},
		{name: "Ion Cannon Turret", type: "turret", qty: 1}
	],
	cost: 1},
	{"TIE Advanced Expansion Pack": [
		{name: "TIE Advanced", type: "ship", qty: 1},
		{name: "Darth Vader", type: "pilot", qty: 1},
		{name: "Maarek Stele", type: "pilot", qty: 1, ship: "TIE Advanced"},
		{name: "Storm Squadron Pilot", type: "pilot", qty: 1},
		{name: "Tempest Squadron Pilot", type: "pilot", qty: 1},
		{name: "Expert Handling", type: "elite", qty: 1},
		{name: "Squad Leader", type: "elite", qty: 1},
		{name: "Swarm Tactics", type: "elite", qty: 1},
		{name: "Cluster Missiles", type: "missile", qty: 1},
		{name: "Concussion Missiles", type: "missile", qty: 1}
	],
	cost: 1},
	{"Millennium Falcon Expansion Pack": [
		{name: "YT-1300", type: "ship", qty: 1},
		{name: "Chewbacca", type: "pilot", qty: 1},
		{name: "Han Solo", type: "pilot", qty: 1},
		{name: "Lando Calrissian", type: "pilot", qty: 1},
		{name: "Outer Rim Smuggler", type: "pilot", qty: 1},
		{name: "Chewbacca", type: "crew", qty: 1},
		{name: "Luke Skywalker", type: "crew", qty: 1},
		{name: "Nien Nunb", type: "crew", qty: 1},
		{name: "Weapons Engineer", type: "crew", qty: 1},
		{name: "Draw Their Fire", type: "elite", qty: 1},
		{name: "Elusiveness", type: "elite", qty: 1},
		{name: "Veteran Instincts", type: "elite", qty: 1},
		{name: "Assault Missiles", type: "missile", qty: 1},
		{name: "Concussion Missiles", type: "missile", qty: 1},
		{name: "Engine Upgrade", type: "modification", qty: 2},
		{name: "Shield Upgrade", type: "modification", qty: 2},
		{name: "Millennium Falcon", type: "title", qty: 1}
	],
	cost: 3},
	{"Slave I Expansion Pack": [
		{name: "Firespray-31", type: "ship", qty: 1},
		{name: "Boba Fett", type: "pilot", variant: "imperial", qty: 1},
		{name: "Kath Scarlet", type: "pilot", variant: "imperial", qty: 1},
		{name: "Krassis Trelix", type: "pilot", qty: 1},
		{name: "Bounty Hunter", type: "pilot", qty: 1},
		{name: "Proximity Mines", type: "bomb", qty: 1},
		{name: "Seismic Charges", type: "bomb", qty: 1},
		{name: "Heavy Laser Cannon", type: "cannon", qty: 1},
		{name: "Ion Cannon", type: "cannon", qty: 1},
		{name: "Gunner", type: "crew", qty: 1},
		{name: "Mercenary Copilot", type: "crew", qty: 1},
		{name: "Expose", type: "elite", qty: 1},
		{name: "Veteran Instincts", type: "elite", qty: 1},
		{name: "Assault Missiles", type: "missile", qty: 1},
		{name: "Homing Missiles", type: "missile", qty: 1},
		{name: "Stealth Device", type: "modification", qty: 2},
		{name: "Slave I", type: "title", qty: 1}
	],
	cost: 3},
	{"A-Wing Expansion Pack": [
		{name: "A-Wing", type: "ship", qty: 1},
		{name: "Arvel Crynyd", type: "pilot", qty: 1},
		{name: "Tycho Celchu", type: "pilot", qty: 1},
		{name: "Green Squadron Pilot", type: "pilot", qty: 1},
		{name: "Prototype Pilot", type: "pilot", qty: 1},
		{name: "Deadeye", type: "elite", qty: 1},
		{name: "Push the Limit", type: "elite", qty: 1},
		{name: "Cluster Missiles", type: "missile", qty: 1},
		{name: "Concussion Missiles", type: "missile", qty: 1},
		{name: "Homing Missiles", type: "missile", qty: 1}
	],
	cost: 1},
	{"TIE Interceptor Expansion Pack": [
		{name: "TIE Interceptor", type: "ship", qty: 1},
		{name: '"Fel\'s Wrath"', type: "pilot", qty: 1},
		{name: "Soontir Fel", type: "pilot", qty: 1},
		{name: "Turr Phennir", type: "pilot", qty: 1},
		{name: "Alpha Squadron Pilot", type: "pilot", qty: 1},
		{name: "Avenger Squadron Pilot", type: "pilot", qty: 1},
		{name: "Saber Squadron Pilot", type: "pilot", qty: 1},
		{name: "Daredevil", type: "elite", qty: 1},
		{name: "Elusiveness", type: "elite", qty: 1}
	],
	cost: 1},
	{"Dice Pack": [], cost: 0},
	{"Rebel Transport Expansion Pack": [
		{name: "X-Wing", type: "ship", qty: 1},
		{name: '"Hobbie" Klivian', type: "pilot", qty: 1},
		{name: "Jek Porkins", type: "pilot", qty: 1},
		{name: "Tarn Mison", type: "pilot", qty: 1},
		{name: "Wes Janson", type: "pilot", qty: 1},
		{name: "Red Squadron Pilot", type: "pilot", qty: 1},
		{name: "Rookie Pilot", type: "pilot", qty: 1},
		{name: "R2-D6", type: "astromech", qty: 1},
		{name: "R3-A2", type: "astromech", qty: 1},
		{name: "R4-D6", type: "astromech", qty: 1},
		{name: "R5-P9", type: "astromech", qty: 1},
		{name: "Flechette Torpedoes", type: "torpedo", qty: 3}
	],
	cost: 6},
	{"HWK-290 Expansion Pack": [
		{name: "HWK-290", type: "ship", qty: 1},
		{name: "Jan Ors", type: "pilot", qty: 1},
		{name: "Kyle Katarn", type: "pilot", qty: 1},
		{name: "Roark Garnet", type: "pilot", qty: 1},
		{name: "Rebel Operative", type: "pilot", qty: 1},
		{name: "Intelligence Agent", type: "crew", qty: 1},
		{name: "Recon Specialist", type: "crew", qty: 1},
		{name: "Saboteur", type: "crew", qty: 1},
		{name: "Moldy Crow", type: "title", qty: 1},
		{name: "Blaster Turret", type: "turret", qty: 1},
		{name: "Ion Cannon Turret", type: "turret", qty: 1}
	],
	cost: 1},
	{"Lambda-Class Shuttle Expansion Pack": [
		{name: "Lambda-Class Shuttle", type: "ship", qty: 1},
		{name: "Captain Kagi", type: "pilot", qty: 1},
		{name: "Captain Yorr", type: "pilot", qty: 1},
		{name: "Colonel Jendon", type: "pilot", qty: 1},
		{name: "Omicron Group Pilot", type: "pilot", qty: 1},
		{name: "Heavy Laser Cannon", type: "cannon", qty: 1},
		{name: "Darth Vader", type: "crew", qty: 1},
		{name: "Flight Instructor", type: "crew", qty: 1},
		{name: "Intelligence Agent", type: "crew", qty: 1},
		{name: "Navigator", type: "crew", qty: 1},
		{name: "Rebel Captive", type: "crew", qty: 1},
		{name: "Weapons Engineer", type: "crew", qty: 1},
		{name: "Advanced Sensors", type: "system", qty: 1},
		{name: "Sensor Jammer", type: "system", qty: 1},
		{name: "Anti-Pursuit Lasers", type: "modification", qty: 2},
		{name: "ST-321", type: "title", qty: 1}
	],
	cost: 3},
	{"B-Wing Expansion Pack": [
		{name: "B-Wing", type: "ship", qty: 1},
		{name: "Ibtisam", type: "pilot", qty: 1},
		{name: "Ten Numb", type: "pilot", qty: 1},
		{name: "Blue Squadron Pilot", type: "pilot", qty: 1},
		{name: "Dagger Squadron Pilot", type: "pilot", qty: 1},
		{name: "Autoblaster", type: "cannon", qty: 1},
		{name: "Ion Cannon", type: "cannon", qty: 1},
		{name: "Fire-Control System", type: "system", qty: 1},
		{name: "Advanced Proton Torpedoes", type: "torpedo", qty: 1},
		{name: "Proton Torpedoes", type: "torpedo", qty: 1}
	],
	cost: 1},
	{"TIE Bomber Expansion Pack": [
		{name: "TIE Bomber", type: "ship", qty: 1},
		{name: "Captain Jonus", type: "pilot", qty: 1},
		{name: "Major Rhymer", type: "pilot", qty: 1},
		{name: "Gamma Squadron Pilot", type: "pilot", qty: 1},
		{name: "Scimitar Squadron Pilot", type: "pilot", qty: 1},
		{name: "Proton Bombs", type: "bomb", qty: 1},
		{name: "Seismic Charges", type: "bomb", qty: 1},
		{name: "Adrenaline Rush", type: "elite", qty: 1},
		{name: "Assault Missiles", type: "missile", qty: 1},
		{name: "Advanced Proton Torpedoes", type: "torpedo", qty: 1}
	],
	cost: 1},
	{"Z-95 Headhunter Expansion Pack": [
		{name: "Z-95 Headhunter", type: "ship", qty: 1},
		{name: "Airen Cracken", type: "pilot", qty: 1},
		{name: "Lieutenant Blount", type: "pilot", qty: 1},
		{name: "Bandit Squadron Pilot", type: "pilot", qty: 1},
		{name: "Tala Squadron Pilot", type: "pilot", qty: 1},
		{name: "Decoy", type: "elite", qty: 1},
		{name: "Wingman", type: "elite", qty: 1},
		{name: "Assault Missiles", type: "missile", qty: 1},
		{name: "Ion Pulse Missiles", type: "missile", qty: 1},
		{name: "Munitions Failsafe", type: "modification", qty: 1}
	],
	cost: 1},
	{"TIE Defender Expansion Pack": [
		{name: "TIE Defender", type: "ship", qty: 1},
		{name: "Colonel Vessery", type: "pilot", qty: 1},
		{name: "Rexler Brath", type: "pilot", qty: 1},
		{name: "Delta Squadron Pilot", type: "pilot", qty: 1},
		{name: "Onyx Squadron Pilot", type: "pilot", qty: 1},
		{name: "Ion Cannon", type: "cannon", qty: 1},
		{name: "Outmaneuver", type: "elite", qty: 1},
		{name: "Predator", type: "elite", qty: 1},
		{name: "Ion Pulse Missiles", type: "missile", qty: 1},
		{name: "Munitions Failsafe", type: "modification", qty: 1}
	],
	cost: 1},
	{"E-Wing Expansion Pack": [
		{name: "E-Wing", type: "ship", qty: 1},
		{name: "Corran Horn", type: "pilot", qty: 1},
		{name: "Etahn A'baht", type: "pilot", qty: 1},
		{name: "Blackmoon Squadron Pilot", type: "pilot", qty: 1},
		{name: "Knave Squadron Pilot", type: "pilot", qty: 1},
		{name: "R7 Astromech", type: "astromech", qty: 1},
		{name: "R7-T1", type: "astromech", qty: 1},
		{name: "Outmaneuver", type: "elite", qty: 1},
		{name: "Advanced Sensors", type: "system", qty: 1},
		{name: "Flechette Torpedoes", type: "torpedo", qty: 1}
	],
	cost: 1},
	{"TIE Phantom Expansion Pack": [
		{name: "TIE Phantom", type: "ship", qty: 1},
		{name: '"Echo"', type: "pilot", qty: 1},
		{name: '"Whisper"', type: "pilot", qty: 1},
		{name: "Shadow Squadron Pilot", type: "pilot", qty: 1},
		{name: "Sigma Squadron Pilot", type: "pilot", qty: 1},
		{name: "Recon Specialist", type: "crew", qty: 1},
		{name: "Tactician", type: "crew", qty: 1},
		{name: "Advanced Cloaking Device", type: "modification", qty: 1},
		{name: "Stygium Particle Accelerator", type: "modification", qty: 1},
		{name: "Fire-Control System", type: "system", qty: 1}
	],
	cost: 1},
	{"Starfield Game Tile Kit": []},
	{"Imperial Aces Expansion Pack": [
		{name: "TIE Interceptor", type: "ship", qty: 2},
		{name: "Carnor Jax", type: "pilot", qty: 1},
		{name: "Kir Kanos", type: "pilot", qty: 1},
		{name: "Lieutenant Lorrir", type: "pilot", qty: 1},
		{name: "Tetran Cowall", type: "pilot", qty: 1},
		{name: "Royal Guard Pilot", type: "pilot", qty: 2},
		{name: "Saber Squadron Pilot", type: "pilot", qty: 2},
		{name: "Opportunist", type: "elite", qty: 2},
		{name: "Push the Limit", type: "elite", qty: 2},
		{name: "Hull Upgrade", type: "modification", qty: 2},
		{name: "Shield Upgrade", type: "modification", qty: 2},
		{name: "Targeting Computer", type: "modification", qty: 2},
		{name: "Royal Guard TIE", type: "title", qty: 2}
	],
	cost: 3},
	{"Tantive IV Expansion Pack": [
		{name: "C-3PO", type: "crew", qty: 1},
		{name: "Han Solo", type: "crew", qty: 1},
		{name: "Leia Organa", type: "crew", qty: 1},
		{name: "R2-D2", type: "crew", qty: 1},
		{name: "Targeting Coordinator", type: "crew", qty: 1}
	],
	cost: 9},
	{"YT-2400 Freighter Expansion Pack": [
		{name: "YT-2400", type: "ship", qty: 1},
		{name: '"Leebo"', type: "pilot", qty: 1},
		{name: "Dash Rendar", type: "pilot", qty: 1},
		{name: "Eaden Vrill", type: "pilot", qty: 1},
		{name: "Wild Space Fringer", type: "pilot", qty: 1},
		{name: "Heavy Laser Cannon", type: "cannon", qty: 1},
		{name: '"Leebo"', type: "crew", qty: 1},
		{name: "Dash Rendar", type: "crew", qty: 1},
		{name: "Lando Calrissian", type: "crew", qty: 1},
		{name: "Gunner", type: "crew", qty: 1},
		{name: "Mercenary Copilot", type: "crew", qty: 1},
		{name: "Lone Wolf", type: "elite", qty: 1},
		{name: "Stay On Target", type: "elite", qty: 1},
		{name: "Proton Rockets", type: "missile", qty: 1},
		{name: "Countermeasures", type: "modification", qty: 2},
		{name: "Experimental Interface", type: "modification", qty: 1},
		{name: "Outrider", type: "title", qty: 1}
	],
	cost: 3},
	{"VT-49 Decimator Expansion Pack": [
		{name: "VT-49 Decimator", type: "ship", qty: 1},
		{name: "Captain Oicunn", type: "pilot", qty: 1},
		{name: "Commander Kenkirk", type: "pilot", qty: 1},
		{name: "Rear Admiral Chiraneau", type: "pilot", qty: 1},
		{name: "Patrol Leader", type: "pilot", qty: 1},
		{name: "Proton Bombs", type: "bomb", qty: 1},
		{name: "Mara Jade", type: "crew", qty: 1},
		{name: "Moff Jerjerrod", type: "crew", qty: 1},
		{name: "Ysanne Isard", type: "crew", qty: 1},
		{name: "Fleet Officer", type: "crew", qty: 1},
		{name: "Intimidation", type: "elite", qty: 1},
		{name: "Ruthlessness", type: "elite", qty: 2},
		{name: "Tactical Jammer", type: "modification", qty: 2},
		{name: "Dauntless", type: "title", qty: 1},
		{name: "Ion Torpedoes", type: "torpedo", qty: 2}
	],
	cost: 4},
	{"StarViper Expansion Pack": [
		{name: "StarViper", type: "ship", qty: 1},
		{name: "Guri", type: "pilot", qty: 1},
		{name: "Prince Xizor", type: "pilot", qty: 1},
		{name: "Black Sun Enforcer", type: "pilot", qty: 1},
		{name: "Black Sun Vigo", type: "pilot", qty: 1},
		{name: "Bodyguard", type: "elite", qty: 1},
		{name: "Calculation", type: "elite", qty: 1},
		{name: "Inertial Dampeners", type: "illicit", qty: 1},
		{name: "Autothrusters", type: "modification", qty: 2},
		{name: "Hull Upgrade", type: "modification", qty: 1},
		{name: "Accuracy Corrector", type: "system", qty: 1},
		{name: "Virago", type: "title", qty: 1},
		{name: "Ion Torpedoes", type: "torpedo", qty: 1}
	],
	cost: 2},
	{"M3-A Interceptor Expansion Pack": [
		{name: "M3-A Interceptor", type: "ship", qty: 1},
		{name: "Laetin A'shera", type: "pilot", qty: 1},
		{name: "Serissu", type: "pilot", qty: 1},
		{name: "Cartel Spacer", type: "pilot", qty: 1},
		{name: "Tansarii Point Veteran", type: "pilot", qty: 1},
		{name: '"Mangler" Cannon', type: "cannon", qty: 1},
		{name: "Flechette Cannon", type: "cannon", qty: 1},
		{name: "Ion Cannon", type: "cannon", qty: 1},
		{name: "Stealth Device", type: "modification", qty: 1},
		{name: '"Heavy Scyk" Interceptor', type: "title", qty: 1}
	],
	cost: 1},
	{"IG-2000 Expansion Pack": [
		{name: "Aggressor", type: "ship", qty: 1},
		{name: "IG-88A", type: "pilot", qty: 1},
		{name: "IG-88B", type: "pilot", qty: 1},
		{name: "IG-88C", type: "pilot", qty: 1},
		{name: "IG-88D", type: "pilot", qty: 1},
		{name: "Proximity Mines", type: "bomb", qty: 1},
		{name: "Seismic Charges", type: "bomb", qty: 1},
		{name: '"Mangler" Cannon', type: "cannon", qty: 1},
		{name: "Autoblaster", type: "cannon", qty: 1},
		{name: '"Hot Shot" Blaster', type: "illicit", qty: 1},
		{name: "Dead Man's Switch", type: "illicit", qty: 2},
		{name: "Feedback Array", type: "illicit", qty: 2},
		{name: "Inertial Dampeners", type: "illicit", qty: 1},
		{name: "Accuracy Corrector", type: "system", qty: 1},
		{name: "IG-2000", type: "title", qty: 1}
	],
	cost: 3},
	{"Most Wanted Expansion Pack": [
		{name: "Y-Wing", type: "ship", qty: 1},
		{name: "Z-95 Headhunter", type: "ship", qty: 2},
		{name: "Boba Fett", type: "pilot", variant: "scum", qty: 1},
		{name: "Dace Bonearm", type: "pilot", qty: 1},
		{name: "Drea Renthal", type: "pilot", qty: 1},
		{name: "Emon Azzameen", type: "pilot", qty: 1},
		{name: "Kaa'to Leeachos", type: "pilot", qty: 1},
		{name: "Kath Scarlet", type: "pilot", variant: "scum", qty: 1},
		{name: "Kavil", type: "pilot", qty: 1},
		{name: "N'Dru Suhlak", type: "pilot", qty: 1},
		{name: "Palob Godalhi", type: "pilot", qty: 1},
		{name: "Torkil Mux", type: "pilot", qty: 1},
		{name: "Binayre Pirate", type: "pilot", qty: 2},
		{name: "Black Sun Soldier", type: "pilot", qty: 2},
		{name: "Hired Gun", type: "pilot", qty: 2},
		{name: "Mandalorian Mercenary", type: "pilot", qty: 1},
		{name: "Spice Runner", type: "pilot", qty: 1},
		{name: "Syndicate Thug", type: "pilot", qty: 2},
		{name: "Greedo", type: "crew", qty: 1},
		{name: "K4 Security Droid", type: "crew", qty: 1},
		{name: "Outlaw Tech", type: "crew", qty: 1},
		{name: '"Hot Shot" Blaster', type: "illicit", qty: 1},
		{name: '"Genius"', type: "salvaged", qty: 1},
		{name: "R4 Agromech", type: "salvaged", qty: 2},
		{name: "R4-B11", type: "salvaged", qty: 1},
		{name: "Salvaged Astromech", type: "salvaged", qty: 2},
		{name: "Unhinged Astromech", type: "salvaged", qty: 2},
		{name: "Andrasta", type: "title", qty: 1},
		{name: "BTL-A4 Y-Wing", type: "title", qty: 2},
		{name: "Bomb Loadout", type: "torpedo", qty: 2},
		{name: "Autoblaster Turret", type: "turret", qty: 2},
	],
	cost: 4},
	{"Rebel Aces Expansion Pack": [
		{name: "A-Wing", type: "ship", qty: 1},
		{name: "B-Wing", type: "ship", qty: 1},
		{name: "Gemmer Sojan", type: "pilot", qty: 1},
		{name: "Jake Farrell", type: "pilot", qty: 1},
		{name: "Keyan Farlander", type: "pilot", qty: 1},
		{name: "Nera Dantels", type: "pilot", qty: 1},
		{name: "Blue Squadron Pilot", type: "pilot", qty: 1},
		{name: "Dagger Squadron Pilot", type: "pilot", qty: 1},
		{name: "Green Squadron Pilot", type: "pilot", qty: 1},
		{name: "Prototype Pilot", type: "pilot", qty: 1},
		{name: "Jan Ors", type: "crew", qty: 1},
		{name: "Kyle Katarn", type: "crew", qty: 1},
		{name: "Chardaan Refit", type: "missile", qty: 3},
		{name: "Proton Rockets", type: "missile", qty: 2},
		{name: "B-Wing/E2", type: "modification", qty: 2},
		{name: "Enhanced Scopes", type: "system", qty: 2},
		{name: "A-Wing Test Pilot", type: "title", qty: 2}
	],
	cost: 3},
	{"Imperial Raider Expansion Pack": [
		{name: "TIE Advanced", type: "ship", qty: 1},
		{name: "Commander Alozen", type: "pilot", qty: 1},
		{name: "Juno Eclipse", type: "pilot", qty: 1},
		{name: "Lieutenant Colzet", type: "pilot", qty: 1},
		{name: "Zertik Strom", type: "pilot", qty: 1},
		{name: "Storm Squadron Pilot", type: "pilot", qty: 1},
		{name: "Tempest Squadron Pilot", type: "pilot", qty: 1},
		{name: "Emperor Palpatine", type: "crew", qty: 1},
		{name: "Cluster Missiles", type: "missile", qty: 1},
		{name: "Proton Rockets", type: "missile", qty: 1},
		{name: "Advanced Targeting Computer", type: "system", qty: 4},
		{name: "TIE/x1", type: "title", qty: 4}
	],
	cost: 10},
	{"Hound's Tooth Expansion Pack": [
		{name: "YV-666", type: "ship", qty: 1},
		{name: "Bossk", type: "pilot", qty: 1},
		{name: "Latts Razzi", type: "pilot", qty: 1},
		{name: "Moralo Eval", type: "pilot", qty: 1},
		{name: "Trandoshan Slaver", type: "pilot", qty: 1},
		{name: "Heavy Laser Cannon", type: "cannon", qty: 1},
		{name: "Bossk", type: "crew", qty: 1},
		{name: "K4 Security Droid", type: "crew", qty: 1},
		{name: "Outlaw Tech", type: "crew", qty: 1},
		{name: "Crack Shot", type: "elite", qty: 1},
		{name: "Lone Wolf", type: "elite", qty: 1},
		{name: "Stay on Target", type: "elite", qty: 1},
		{name: "Glitterstim", type: "illicit", qty: 1},
		{name: "Engine Upgrade", type: "modification", qty: 1},
		{name: "Ion Projector", type: "modification", qty: 2},
		{name: "Maneuvering Fins", type: "modification", qty: 1},
		{name: "Hound's Tooth", type: "title", qty: 1}
	],
	cost: 4},
	{"Kihraxz Fighter Expansion Pack": [
		{name: "Kihraxz Fighter", type: "ship", qty: 1},
		{name: "Graz the Hunter", type: "pilot", qty: 1},
		{name: "Talonbane Cobra", type: "pilot", qty: 1},
		{name: "Black Sun Ace", type: "pilot", qty: 1},
		{name: "Cartel Marauder", type: "pilot", qty: 1},
		{name: "Crack Shot", type: "elite", qty: 1},
		{name: "Lightning Reflexes", type: "elite", qty: 1},
		{name: "Predator", type: "elite", qty: 1},
		{name: "Glitterstim", type: "illicit", qty: 1},
		{name: "Homing Missiles", type: "missile", qty: 1}
	],
	cost: 1},
	{"K-Wing Expansion Pack": [
		{name: "K-Wing", type: "ship", qty: 1},
		{name: "Esege Tuketu", type: "pilot", qty: 1},
		{name: "Miranda Doni", type: "pilot", qty: 1},
		{name: "Guardian Squadron Pilot", type: "pilot", qty: 1},
		{name: "Warden Squadron Pilot", type: "pilot", qty: 1},
		{name: "Conner Net", type: "bomb", qty: 1},
		{name: "Ion Bombs", type: "bomb", qty: 1},
		{name: "Bombardier", type: "crew", qty: 1},
		{name: "Advanced Homing Missiles", type: "missile", qty: 1},
		{name: "Advanced SLAM", type: "modification", qty: 1},
		{name: "Extra Munitions", type: "torpedo", qty: 1},
		{name: "Plasma Torpedoes", type: "torpedo", qty: 1},
		{name: "Twin Laser Turret", type: "turret", qty: 2}
	],
	cost: 2},
	{"TIE Punisher Expansion Pack": [
		{name: "TIE Punisher", type: "ship", qty: 1},
		{name: '"Deathrain"', type: "pilot", qty: 1},
		{name: '"Redline"', type: "pilot", qty: 1},
		{name: "Black Eight Squadron Pilot", type: "pilot", qty: 1},
		{name: "Cutlass Squadron Pilot", type: "pilot", qty: 1},
		{name: "Cluster Mines", type: "bomb", qty: 1},
		{name: "Ion Bombs", type: "bomb", qty: 1},
		{name: "Advanced Homing Missiles", type: "missile", qty: 1},
		{name: "Twin Ion Engine Mk. II", type: "modification", qty: 2},
		{name: "Enhanced Scopes", type: "system", qty: 1},
		{name: "Extra Munitions", type: "torpedo", qty: 1},
		{name: "Flechette Torpedoes", type: "torpedo", qty: 1},
		{name: "Plasma Torpedoes", type: "torpedo", qty: 1}
	],
	cost: 2},
	{"Imperial Assault Carrier Expansion Pack": [
		{name: "TIE Fighter", type: "ship", qty: 2},
		{name: '"Chaser"', type: "pilot", qty: 1},
		{name: '"Scourge"', type: "pilot", qty: 1},
		{name: '"Wampa"', type: "pilot", qty: 1},
		{name: '"Youngster"', type: "pilot", qty: 1},
		{name: "Academy Pilot", type: "pilot", qty: 2},
		{name: "Black Squadron Pilot", type: "pilot", qty: 2},
		{name: "Obsidian Squadron Pilot", type: "pilot", qty: 2},
		{name: "Agent Kallus", type: "crew", qty: 1},
		{name: "Expert Handling", type: "elite", qty: 1},
		{name: "Expose", type: "elite", qty: 1},
		{name: "Marksmanship", type: "elite", qty: 1}
	],
	cost: 7},
	{"The Force Awakens Core Set": [
		{name: "T-70 X-Wing", type: "ship", qty: 1},
		{name: "TIE/fo Fighter", type: "ship", qty: 2},
		{name: '"Blue Ace"', type: "pilot", qty: 1},
		{name: '"Epsilon Leader"', type: "pilot", qty: 1},
		{name: '"Omega Ace"', type: "pilot", qty: 1},
		{name: '"Zeta Ace"', type: "pilot", qty: 1},
		{name: "Poe Dameron", type: "pilot", qty: 1},
		{name: "Blue Squadron Novice", type: "pilot", qty: 1},
		{name: "Epsilon Squadron Pilot", type: "pilot", qty: 2},
		{name: "Omega Squadron Pilot", type: "pilot", qty: 2},
		{name: "Red Squadron Veteran", type: "pilot", qty: 1},
		{name: "Zeta Squadron Pilot", type: "pilot", qty: 2},
		{name: "BB-8", type: "astromech", qty: 1},
		{name: "R5-X3", type: "astromech", qty: 1},
		{name: "Wired", type: "elite", qty: 1},
		{name: "Weapons Guidance", type: "tech", qty: 1},
		{name: "Proton Torpedoes", type: "torpedo", qty: 1}
	],
	cost: 4},
	{"T-70 X-wing Expansion Pack": [
		{name: "T-70 X-Wing", type: "ship", qty: 1},
		{name: 'Ello Asty', type: "pilot", qty: 1},
		{name: '"Red Ace"', type: "pilot", qty: 1},
		{name: 'Blue Squadron Novice', type: "pilot", qty: 1},
		{name: 'Red Squadron Veteran', type: "pilot", qty: 1},
		{name: "Cool Hand", type: "elite", qty: 1},
		{name: "Targeting Astromech", type: "astromech", qty: 1},
		{name: "Integrated Astromech", type: "modification", qty: 1},
		{name: "Weapons Guidance", type: "tech", qty: 1},
		{name: "Advanced Proton Torpedoes", type: "torpedo", qty: 1}
	],
	cost: 1},
	{"TIE/fo Fighter Expansion Pack": [
		{name: "TIE/fo Fighter", type: "ship", qty: 1},
		{name: '"Epsilon Ace"', type: "pilot", qty: 1},
		{name: '"Omega Leader"', type: "pilot", qty: 1},
		{name: '"Zeta Leader"', type: "pilot", qty: 1},
		{name: "Epsilon Squadron Pilot", type: "pilot", qty: 1},
		{name: "Omega Squadron Pilot", type: "pilot", qty: 1},
		{name: "Zeta Squadron Pilot", type: "pilot", qty: 1},
		{name: "Juke", type: "elite", qty: 1},
		{name: "Comm Relay", type: "tech", qty: 1}
	],
	cost: 1},
	{"Ghost Expansion Pack": [
		{name: "VCX-100", type: "ship", qty: 1},
		{name: "Hera Syndulla", type: "pilot", qty: 1, ship: "VCX-100"},
		{name: "Kanan Jarus", type: "pilot", qty: 1},
		{name: '"Chopper"', type: "pilot", qty: 1},
		{name: "Lothal Rebel", type: "pilot", qty: 1},
		{name: "Attack Shuttle", type: "ship", qty: 1},
		{name: "Hera Syndulla", type: "pilot", qty: 1, ship: "Attack Shuttle"},
		{name: "Sabine Wren", type: "pilot", qty: 1, ship: "Attack Shuttle"},
		{name: "Ezra Bridger", type: "pilot", qty: 1},
		{name: '"Zeb" Orrelios', type: "pilot", qty: 1},
		{name: "Predator", type: "elite", qty: 1},
		{name: "Adv. Proton Torpedoes", type: "torpedo", qty: 1},
		{name: "Dorsal Turret", type: "turret", qty: 2},
		{name: "Conner Net", type: "bomb", qty: 1},
		{name: "Thermal Detonators", type: "bomb", qty: 1},
		{name: "Cluster Mines", type: "bomb", qty: 1},
		{name: "Hera Syndulla", type: "crew", qty: 1},
		{name: "Kanan Jarus", type: "crew", qty: 1},
		{name: '"Chopper"', type: "crew", qty: 1},
		{name: "Sabine Wren", type: "crew", qty: 1},
		{name: "Ezra Bridger", type: "crew", qty: 1},
		{name: '"Zeb" Orrelios', type: "crew", qty: 1},
		{name: "Reinforced Deflectors", type: "system", qty: 1}
	],
	 cost: 5},
	{"Inquisitor's TIE Expansion Pack": [
		{name: "Tie Advanced Prototype", type: "ship", qty: 1},
		{name: "Valen Rudor", type: "pilot", qty: 1},
		{name: "Baron of the Empire", type: "pilot", qty: 1},
		{name: "Sienar Test Pilot", type: "pilot", qty: 1},
		{name: "Deadeye", type: "elite", qty: 1},
		{name: "Homing Missiles", type: "missile", qty: 1},
		{name: "XX-23 S-Thread Tracers", type: "missile", qty: 1},
		{name: "Guidance Chips", type: "modification", qty: 1},
		{name: "TIE/v1", type: "title", qty: 1}
	], cost: 1},
	{"Mist Hunter Expansion Pack": [
		{name: "G-1A Starfighter", type: "ship", qty: 1},
		{name: "Zuckuss", type: "pilot", qty: 1},
		{name: "4-LOM", type: "pilot", qty: 1},
		{name: "Gand Findsman", type: "pilot", qty: 1},
		{name: "Ruthless Freelancer", type: "pilot", qty: 1},
		{name: "4-LOM", type: "crew", qty: 1},
		{name: "Zuckuss", type: "crew", qty: 1},
		{name: "Adaptabillity", type: "elite", qty: 2},
		{name: "Tractor Beam", type: "cannon", qty: 1},
		{name: "Cloaking Device", type: "illicit", qty: 1},
		{name: "Electronic Baffle", type: "system", qty: 2},
		{name: "Mist Hunter", type: "title", qty: 1}
	], cost: 2},
	{"Punishing One Expansion Pack": [
		{name: "JumpMaster 5000", type: "ship", qty: 1},
		{name: "Tel Trevura", type: "pilot", qty: 1},
		{name: "Manaroo", type: "pilot", qty: 1},
		{name: "Contracted Scout", type: "pilot", qty: 1},
		{name: '"Gonk"', type: "crew", qty: 1},
		{name: "Boba Fett", type: "crew", qty: 1},
		{name: "Dengar", type: "crew", qty: 1},
		{name: "Rage", type: "elite", qty: 1},
		{name: "Attanni Mindlink", type: "elite", qty: 2},
		{name: "Plasma Torpedoes", type: "torpedo", qty: 1},
		{name: "R5-P8", type: "salvaged", qty: 1},
		{name: "Overclocked R4", type: "salvaged", qty: 2},
		{name: "Punishing One", type: "title", qty: 1},
		{name: "Feedback Array", type: "illicit", qty: 1},
		{name: "Guidance Chips", type: "modification", qty: 2}
	], cost: 3},
	{"Blue Bases and Pegs": [], cost: 0},
	{"Red Bases and Pegs": [], cost: 0},
	{"Green Bases and Pegs": [], cost: 0},
	{"Purple Bases and Pegs": [], cost: 0},
	{"Orange Bases and Pegs": [], cost: 0},
	{"Clear Bases and Pegs": [], cost: 0},
	{"Rebel Maneuver Dial Upgrade Kit": [], cost: 0},
	{"Imperial Maneuver Dial Upgrade Kit": [], cost: 0},
	{"Scum Maneuver Dial Upgrade Kit": [], cost: 0},
	{"Imperial Veterans Expansion Pack": [
		{name: "Tie Defender", type: "ship", qty: 1},
		{name: "Maarek Stele-SWX52", type: "pilot", qty: 1, ship: "Tie Defender"},
		{name: "Countess Ryad", type: "pilot", qty: 1},
		{name: "Glaive Squadron Pilot", type: "pilot", qty: 2},
		{name: "Tie Bomber", type: "ship", qty: 1},
		{name: "Tomax Bren", type: "pilot", qty: 1},
		{name: '"Deathfire"', type: "pilot", qty: 1},
		{name: "Gamma Squadron Veteran", type: "pilot", qty: 2},
		{name: "Crack Shot", type: "elite", qty: 1},
		{name: "Dorsal Turret", type: "turret", qty: 2},
		{name: "Proximity Miness", type: "bomb", qty: 1},
		{name: "Cluster Mines", type: "bomb", qty: 1},
		{name: "Tractor Beam", type: "cannon", qty: 1},
		{name: "Systems Officer", type: "crew", qty: 1},
		{name: "TIE/x7", type: "title", qty: 2},
		{name: "TIE/D", type: "title", qty: 2},
		{name: "TIE Shuttle", type: "title", qty: 2},
		{name: "Long Range Scanners", type: "modification", qty: 2}
	], cost: 3},
	{"ARC-170 Expansion Pack": [
		{name: "ARC-170", type: "ship", qty: 1},
		{name: "Norra Wexley", type: "pilot", qty: 1},
		{name: "Shara Bey", type: "pilot", qty: 1},
		{name: "Thane Kyrell", type: "pilot", qty: 1},
		{name: "Braylen Stramm", type: "pilot", qty: 1},
		{name: "Tail Gunner", type: "crew", qty: 1},
		{name: "Recon Specialist", type: "crew", qty: 1},
		{name: "Adrenaline Rush", type: "elite", qty: 1},
		{name: "Seismic Torpedoes", type: "torpedo", qty: 1},
		{name: "R3 Astromech", type: "astromech", qty: 2},
		{name: "Alliance Overhaul", type: "title", qty: 1},
		{name: "Vectored Thrusters", type: "modification", qty: 2}
	], cost: 2},
	{"Special Forces TIE Expansion Pack": [
		{name: "Tie/sf Fighter", type: "ship", qty: 1},
		{name: '"Quickdraw"', type: "pilot", qty: 1},
		{name: '"Backdraft"', type: "pilot", qty: 1},
		{name: "Omega Specialist", type: "pilot", qty: 1},
		{name: "Zeta Specialist", type: "pilot", qty: 1},
		{name: "Wired", type: "elite", qty: 1},
		{name: "Collision Detector", type: "system", qty: 1},
		{name: "Sensor Cluster", type: "tech", qty: 2},
		{name: "Special Ops Training", type: "title", qty: 1}
	], cost: 1},
	{"Protectorate Starfighter Expansion Pack": [
		{name: "Protectorate Starfighter", type: "ship", qty: 1},
		{name: "Fenn Rau", type: "pilot", qty: 1},
		{name: "Old Teroch", type: "pilot", qty: 1},
		{name: "Kad Solus", type: "pilot", qty: 1},
		{name: "Concord Dawn Ace", type: "pilot", qty: 1},
		{name: "Concord Dawn Veteran", type: "pilot", qty: 1},
		{name: "Zealous Recruit", type: "pilot", qty: 1},
		{name: "Fearlessness", type: "elite", qty: 1},
		{name: "Concord Dawn Protector", type: "title", qty: 1}
	], cost: 1},
	{"Shadow Caster Expansion Pack": [
		{name: "Lancer-class Pursuit Craft", type: "ship", qty: 1},
		{name: "Ketsu Onyo", type: "pilot", qty: 1},
		{name: "Asajj Ventress", type: "pilot", qty: 1},
		{name: "Sabine Wren-SWX56", type: "pilot", qty: 1, ship: "Lancer-class Pursuit Craft"},
		{name: "Shadowport Hunter", type: "pilot", qty: 1},
		{name: "Latts Razzi", type: "crew", qty: 1},
		{name: "Ketsu Onyo", type: "crew", qty: 1},
		{name: "IG-88D", type: "crew", qty: 1},
		{name: "Veteran Instincts", type: "elite", qty: 1},
		{name: "Rigged Cargo Chute", type: "illicit", qty: 1},
		{name: "Black Market Slicer Tools", type: "illicit", qty: 2},
		{name: "Shadow Caster", type: "title", qty: 1},
		{name: "Countermeasures", type: "modification", qty: 1},
		{name: "Tactical Jammer", type: "modification", qty: 2},
		{name: "Gyroscopic Targeting", type: "modification", qty: 1}
	], cost: 4},
	{"Heroes of the Resistance Expansion Pack": [], cost: 4},
	{"null": []},
	{"Sabine's TIE Fighter Expansion Pack": [], cost: 1},
	{"Upsilon-class Shuttle Expansion Pack": [], cost: 4},
	{"Quadjumper Expansion Pack": [], cost: 1},
	{"U-Wing Expansion Pack": [], cost: 3},
	{"TIE Striker Expansion Pack": [], cost: 1}
];
